##
## PIN tools
##


include makefile.config


DBG=
OPT=-O3
CXX = g++
CXXFLAGS = -Wall -c -Werror -Wno-unknown-pragmas $(DBG) $(OPT)

TOOLS = rdpersig

all: $(TOOLS)

## build rules

rdpersig.o : rdpersig.C ScaleTree/analyze.c ScaleTree/hash.cxx ScaleTree/counter.cxx
	$(CXX) -c $(CXXFLAGS) $(PIN_CXXFLAGS) -o $@ $<
rdpersig: rdpersig.o
	$(CXX) $(PIN_LDFLAGS) -o $@ $< $(PIN_LIBS)

## cleaning
clean:
	-rm -f *.o $(TOOLS) *.out *.tested *.failed
